name: Validate XML

on:
  push:
    branches:
      - '**'
    paths:
      - '**.xml'

  pull_request:
    paths:
      - '**.xml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Validate all XML files
        run: |
          find . -name "*.xml" -print0 | xargs -0 -n1 xmllint --noout
